### ISSUE TITLE
Error when try to get ir.attachment

### ISSUE THREAD

**Issue by jsebasmuller** [skilld-labs/go-odoo#39] opened 2023-03-30 15:12 UTC
Hello friends, I am trying to obtain the ir.attachment model that is related to the sale.order, I am already obtaining the id and name of the relationship but when obtaining all the fields of the ir.attachment by id, it fails me with the following mistake:

"reading body XML syntax error on line 88: illegal character code U+000C"

I would be very grateful if you could help me,

Thank you very much for the help

**Comment by ahuret** [comment] 2023-03-30 15:37
Hello @jsebasmuller , it looks like there's an illegal caracter in the http response, could you please provider a dump of the response ?

**Comment by jsebasmuller** [comment] 2023-03-30 15:56
Hello @ahuret I am doing the direct query with the go-odoo library with the following method:

attachment, err := r.conn.GetIrAttachment(idAttachment)

in the err is directly the message that I sent from the error of this post

**Comment by ahuret** [comment] 2023-03-30 16:15
I was not able to reproduce when I tried to add this caracter... can you please provide more context ? which version of go-odoo are you using ? maybe you can share the concerning file too ? So I can reproduce and debug.

**Comment by ahuret** [comment] 2023-03-30 16:58
Actually, the code is working as expected but issue here is about the ir_attachment itself which have invalid character. I believe the invalid character come from the file related to this attachment itself. This is related to the xmlrpc client we use that try to parse the received xml. Maybe you can share the file with me (in private) so I can try to reproduce using my odoo instance ?

**Comment by ahuret** [comment] 2023-04-06 11:44
closing it for now
feel free to open it again if you think this it still relevant

**Closed by ahuret** 2023-04-06 11:44 UTC

**Comment by jsebasmuller** [comment] 2023-04-11 21:25
Hello @ahuret, I share the file that I download directly from the odoo website, this same file is the one that fails to download with the code that I shared earlier, I hope you can reproduce the error so that you can help me.

https://drive.google.com/file/d/1OP5H8UTUzULXzH3e3cf6pm_ewmV_rmiv/view?usp=sharing

**Comment by jsebasmuller** [comment] 2023-04-11 22:06
I was finally able to get the file but it was consuming the endpoint directly from odoo with postman, here I leave you the answer to see if you can see what is wrong so that it fails in the response of the library

I leave you here the link of the json that returns me

https://drive.google.com/file/d/1mSR5epH2_lu0Vsrub_6VTyX5Yibw3Piw/view?usp=share_link
